# Generated by Django 5.0.3 on 2024-03-09 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_alter_githubmodel_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubmodel',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='githubmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='githubmodel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='githubmodel',
            name='public_repos',
        ),
    ]
