# Generated by Django 5.0.3 on 2024-03-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_remove_githubmodel_bio_remove_githubmodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubmodel',
            name='bio',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Bio do usuário'),
        ),
        migrations.AddField(
            model_name='githubmodel',
            name='email',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='email do Usuário'),
        ),
        migrations.AddField(
            model_name='githubmodel',
            name='location',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='localização do Usuário'),
        ),
        migrations.AddField(
            model_name='githubmodel',
            name='public_repos',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Repositórios Publicos'),
        ),
    ]
