# Generated by Django 5.0.3 on 2024-03-09 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_githubmodel_bio_githubmodel_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubmodel',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='githubmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='githubmodel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='githubmodel',
            name='login',
        ),
        migrations.RemoveField(
            model_name='githubmodel',
            name='public_repos',
        ),
    ]
