# Generated by Django 5.0.3 on 2024-03-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0007_remove_githubmodel_bio_remove_githubmodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubmodel',
            name='login',
            field=models.CharField(default=2, max_length=25, verbose_name='Nome do usuário'),
            preserve_default=False,
        ),
    ]
